import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="flex flex-col justify-center items-center h-screen">
          <h1 className="text-6xl font-bold text-slate-900">
            Web3 YouTube Clone
          </h1>
          <h3 className="text-2xl mt-8 text-slate-900">
            Next.js, TailwindCSS, Solidity, IPFS, The Graph and Polygon
          </h3>
        </div>
      </main>
    </div>
  );
}
